<?php
/**
 * @file
 * A description of what your module does.
 */

/**
 * Implements hook_element_info().
 */
function ip_address_form_element_element_info() {

  return array(
    'ipv4_address_field' => array(
      '#input' => true,
      '#process' => array('ipv4_address_form_element_process'),
      '#theme_wrappers' => array('fieldset'),
    ),
    'ipv4_address_range_field' => array(
      '#input' => true,
      '#process' => array('ipv4_address_range_form_element_process'),
      '#element_validate' => array('ipv4_address_range_form_element_validate'),
      '#theme_wrappers' => array('fieldset'),
    ),
    'ipv6_address_field' => array(
      '#input' => true,
      '#process' => array('ipv6_address_form_element_process'),
      '#theme_wrappers' => array('fieldset'),
    ),
    'ipv6_address_range_field' => array(
      '#input' => true,
      '#process' => array('ipv6_address_range_form_element_process'),
      '#element_validate' => array('ipv6_address_range_form_element_validate'),
      '#theme_wrappers' => array('fieldset'),
    ),
  );
}



function ipv4_address_form_element_process($element, &$form_state) {

  $element['ip_address'] = array(
    '#attributes' => array('class' => array('ipv4')),
    '#type' => 'textfield',
    '#default_value' => null,
  );

  return $element;
}



function ipv4_address_range_form_element_validate(&$element, &$form_state) {

  $ip = &$form_state['input'];

  foreach($element['#parents'] as $key => $value) {
    $ip = &$ip[$value];
  }

  if(ip2long($ip['ip_range_start']) > ip2long($ip['ip_range_end'])) {
    form_error($element, t('Start address must be smaller rather end address.'));

    return;
  }
}



function ipv6_address_form_element_process($element, &$form_state) {

  $element['ip_address'] = array(
    '#attributes' => array('class' => array('ipv6')),
    '#type' => 'textfield',
    '#default_value' => null,
  );

  return $element;
}



function ipv6_address_range_form_element_validate(&$element, &$form_state) {

  $ip = &$form_state['input'];

  foreach($element['#parents'] as $key => $value) {
    $ip = &$ip[$value];
  }

  if(inet_pton($ip['ip_range_start']) > inet_pton($ip['ip_range_end'])) {
    form_error($element, t('Start address must be smaller rather end address.'));

    return;
  }
}



function ipv4_address_range_form_element_process(&$element, &$form_state) {

  $element['ip_range_start'] = array(
    '#title' => t('Start'),
    '#attributes' => array('class' => array('ipv4')),
    '#type' => 'textfield',
    '#default_value' => null,
  );

  $element['ip_range_end'] = array(
    '#title' => t('End'),
    '#attributes' => array('class' => array('ipv4')),
    '#type' => 'textfield',
    '#default_value' => null,
  );

  return $element;

}



function ipv6_address_range_form_element_process(&$element, &$form_state) {

  $element['ip_range_start'] = array(
    '#title' => t('Start'),
    '#attributes' => array('class' => array('ipv6')),
    '#type' => 'textfield',
    '#default_value' => null,
  );

  $element['ip_range_end'] = array(
    '#title' => t('End'),
    '#attributes' => array('class' => array('ipv6')),
    '#type' => 'textfield',
    '#default_value' => null,
  );

  return $element;

}