<?php
/**
 * @file
 * A description of what your module does.
 */

/**
 * Implements hook_element_info().
 */
function ip_address_form_element_element_info() {

  return array(
    'ipv4_address_field' => array(
      '#input' => true,
      '#process' => array('ipv4_address_form_element_process'),
      '#theme_wrappers' => array('fieldset'),
    ),
    'ipv4_address_range_field' => array(
      '#input' => true,
      '#process' => array('ipv4_address_range_form_element_process'),
      '#element_validate' => array('ipv4_address_range_form_element_validate'),
      '#theme_wrappers' => array('fieldset'),
    ),
    'ipv6_address_field' => array(
      '#input' => true,
      '#process' => array('ipv6_address_form_element_process'),
      '#theme_wrappers' => array('fieldset'),
    ),
    'ipv6_address_range_field' => array(
      '#input' => true,
      '#process' => array('ipv6_address_range_form_element_process'),
      '#element_validate' => array('ipv6_address_range_form_element_validate'),
      '#theme_wrappers' => array('fieldset'),
    ),
  );
}



function ipv4_address_form_element_process($element, &$form_state) {

  $element['ip_address'] = array(
    '#attributes' => array('class' => array('ipv4')),
    '#type' => 'textfield',
    '#default_value' => null,
  );

  return $element;
}



function ipv4_address_range_form_element_validate(&$element, &$form_state) {

  $where = &$form_state['input'];

  foreach($element['#parents'] as $key => $value) {
    $where = &$where[$value];
  }

  $start = explode('.', $where['ip_range_start']);
  $end = explode('.', $where['ip_range_end']);

  foreach($start as $key => $mask_element) {
    if($start[$key] > $end[$key]) {
      form_error($element, t('Start address must be smaller rather end address.'));

      return;
    }
  }
}



function ipv6_address_form_element_process($element, &$form_state) {

  $element['ip_address'] = array(
    '#attributes' => array('class' => array('ipv6')),
    '#type' => 'textfield',
    '#default_value' => null,
  );

  return $element;
}



function ipv6_address_range_form_element_validate(&$element, &$form_state) {

  $where = &$form_state['input'];

  foreach($element['#parents'] as $key => $value) {
    $where = &$where[$value];
  }

  $start = explode(':', $where['ip_range_start']);
  $end = explode(':', $where['ip_range_end']);

  foreach($start as $key => $mask_element) {
    if(hexdec($start[$key]) > hexdec($end[$key])) {
      form_error($element, t('Start address must be smaller rather end address.'));

      return;
    }
  }
}



function ipv4_address_range_form_element_process(&$element, &$form_state) {

  $element['ip_range_start'] = array(
    '#title' => t('Start'),
    '#attributes' => array('class' => array('ipv4')),
    '#type' => 'textfield',
    '#default_value' => null,
  );

  $element['ip_range_end'] = array(
    '#title' => t('End'),
    '#attributes' => array('class' => array('ipv4')),
    '#type' => 'textfield',
    '#default_value' => null,
  );

  return $element;

}



function ipv6_address_range_form_element_process(&$element, &$form_state) {

  $element['ip_range_start'] = array(
    '#title' => t('Start'),
    '#attributes' => array('class' => array('ipv6')),
    '#type' => 'textfield',
    '#default_value' => null,
  );

  $element['ip_range_end'] = array(
    '#title' => t('End'),
    '#attributes' => array('class' => array('ipv6')),
    '#type' => 'textfield',
    '#default_value' => null,
  );

  return $element;

}